// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UzywaneKsiazki.Models.DomainModels;
using UzywaneKsiazki.Models.Repository;

namespace UzywaneKsiazki.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180520104636_user")]
    partial class user
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("UzywaneKsiazki.Models.DomainModels.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<string>("AuthorName");

                    b.Property<string>("BookAuthor");

                    b.Property<DateTime>("DateOfPosting");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("PhotosDb");

                    b.Property<decimal>("Price");

                    b.Property<string>("PublishDate");

                    b.Property<string>("SearchTags");

                    b.Property<string>("StateOfBook");

                    b.Property<string>("Telephone");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("UzywaneKsiazki.Models.DomainModels.User", b =>
                {
                    b.Property<string>("Nickname")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<int>("Role");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Nickname");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
